---
apiVersion: v1
kind: Service
metadata:
  name: kanidm
  labels:
    app.kubernetes.io/name: kanidm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kanidm
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
---
apiVersion: v1
kind: Service
metadata:
  name: kanidm-node
  labels:
    app.kubernetes.io/name: kanidm-node
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: kanidm
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      nodePort: 30123
