---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: paperless
      app.kubernetes.io/managed-by: kustomize
    includeTemplates: true

namespace: paperless
resources:
  - namespace.yml
  - paperless
  - redis

images:
  - name: paperless
    newName: ghcr.io/paperless-ngx/paperless-ngx
    newTag: 2.19.5
  - name: redis
    newName: docker.io/library/redis
    newTag: 8.2.3-alpine
