# vim: ft=yaml.ansible
---
argument_specs:
  main:
    options:
      pxe_server_compose_name:
        type: str
        required: true
      pxe_server_ssh_authorized_key:
        type: 'str'
        required: true

