---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jellyfin
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pv-data.yml
  - pv-media.yml

images:
  - name: jellyfin
    newName: ghcr.io/jellyfin/jellyfin
    newTag: 10.10.7
