name: CI - Ansible
on:
  push:
    branches:
      - main
    paths:
      - 0-baremetal/**
      - 1-os/**
      - 2-argocd/playbook_main.yml
      - .github/workflows/ansible.yml
  workflow_dispatch:

jobs:
  lint_playbooks:
    name: Lint Ansible playbooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.20.3
        with:
          setup_python: true
          args: ./0-baremetal ./1-os ./2-argocd/playbook_main.yml
